INSERT INTO `skills` (`slug`, `name`, `category`, `sort_order`) VALUES
  ('ui-ux-design', 'UI/UX Design', 'Design', 10),
  ('web-design', 'Web Design', 'Design', 20),
  ('product-design', 'Product Design', 'Design', 30),
  ('branding', 'Branding', 'Design', 40),
  ('creative-direction', 'Creative Direction', 'Design', 50),
  ('frontend-development', 'Front-end Development', 'Development', 110),
  ('backend-development', 'Back-end Development', 'Development', 120),
  ('full-stack-development', 'Full-stack Development', 'Development', 130),
  ('mobile-development', 'Mobile App Development', 'Development', 140),
  ('devops-deployment', 'Deployment & Hosting', 'Development', 150),
  ('code-review', 'Code Review', 'Quality', 210),
  ('qa-testing', 'QA & Testing', 'Quality', 220),
  ('security-review', 'Security Review', 'Quality', 230),
  ('performance', 'Performance', 'Quality', 240),
  ('accessibility', 'Accessibility', 'Quality', 250),
  ('copywriting', 'Copywriting', 'Content', 310),
  ('editing', 'Editing', 'Content', 320),
  ('seo', 'SEO', 'Content', 330);
